[package]
name = "tessera-term"
version.workspace = true
edition.workspace = true
license.workspace = true
publish = false

[dependencies]
wezterm-term = { git = "https://github.com/wezterm/wezterm", rev = "577474d89ee6", default-features = false }
tessera-render = { path = "../render" }
anyhow = { workspace = true }
tokio = { workspace = true }

[dev-dependencies]
